### pandas

In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.1-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting numpy>=2.3.3 (from pandas)
  Using cached numpy-2.4.3-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/preetam/Desktop/pylibry/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/preetam/Desktop/pylibry/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.1-cp314-cp314-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 8.0 MB/s  0:00:01m0:00:0100:01m
Using cached numpy-2.4.3-cp314-cp314-macosx_14_0_arm64.whl (5.2 MB)
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.3 pandas-3.0.1

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [9]:
import numpy as np 
import pandas as pd

ModuleNotFoundError: No module named 'numpy'

---
### creating series and panda series

In [3]:
labels = ['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={1:10,2:20,3:30}

In [4]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(my_list,index=arr)

10    10
20    20
30    30
dtype: int64

---
### dataframes

In [ ]:
data ={
    'name':['john','jolli','peter'],
    'age':[23,24,25],
    'city':['new york','los angeles','chicago'],
    'salary':[2000,2500,3000]
    
}
df = pd.DataFrame(data)

    name  age         city  salary
0   john   23     new york    2000
1  jolli   24  los angeles    2500
2  peter   25      chicago    3000

In [13]:
data_list=[
    ['john',32,'male'],
    ['jane',28,'female'],
    ['mark',45,'male']
]
df2=pd.DataFrame(data_list)
columns=['name','age','gender']
df2=pd.DataFrame(data_list,columns=columns)
print(df2)

NameError: name 'pd' is not defined

---
### selection and indexing of col

In [14]:
df2

   name  age  gender
0  john   32    male
1  jane   28  female
2  mark   45    male

In [20]:
df2['name']
df2[['name','age']]

   name  age
0  john   32
1  jane   28
2  mark   45

---
### creating new col

In [22]:
df2["designation"]=["doctor","nurse","nurse"]

NameError: name 'df2' is not defined

---
### remove col

In [34]:
df2.drop('designation', axis=1, inplace=True)

df2

KeyError: "['Designation'] not found in axis"

In [4]:

print("abs")

abs