# group by aggregation

In [3]:
import numpy as np 
import pandas as pd

In [4]:
data = {
    'Category': ['A','B','A','B','A','B','A','B'],
    'Store':['S1','S1','S2','S2','S1','S2','S2','S1'],
    'Quantity':[10,15,12,18,8,20,15,25],
    'Date':pd.date_range('2023-01-01', periods=8)



}
df = pd.DataFrame(data)
df

  Category Store  Quantity       Date
0        A    S1        10 2023-01-01
1        B    S1        15 2023-01-02
2        A    S2        12 2023-01-03
3        B    S2        18 2023-01-04
4        A    S1         8 2023-01-05
5        B    S2        20 2023-01-06
6        A    S2        15 2023-01-07
7        B    S1        25 2023-01-08

In [5]:
# Group by store and calculate the sum pf the sales
cat = df.groupby('Category')['Quantity'].sum()
print(cat)

Category
A    45
B    78
Name: Quantity, dtype: int64

In [6]:
# group by multiple columns
cat = df.groupby(['Category','Store'])['Quantity'].sum()
print(cat)

Category  Store
A         S1       18
          S2       27
B         S1       40
          S2       38
Name: Quantity, dtype: int64

In [ ]:
df['Quantity'].mean()
#median mean  min max count std

np.float64(15.375)

In [10]:
df['Quantity'].agg(['mean','min','max'])

mean    15.375
min      8.000
max     25.000
Name: Quantity, dtype: float64

---
## pivot tables

In [11]:


data = [
    ['2023-01-01', 'A', 'East', 825, 26, 'John', 'January', 'Q1'],
    ['2023-01-02', 'B', 'West', 611, 51, 'Mary', 'January', 'Q1'],
    ['2023-01-03', 'C', 'North', 768, 11, 'Bob', 'January', 'Q1'],
    ['2023-01-04', 'D', 'South', 665, 71, 'Alice', 'January', 'Q1'],
    ['2023-01-05', 'A', 'East', 157, 20, 'John', 'January', 'Q1'],
    ['2023-01-06', 'B', 'West', 436, 43, 'Mary', 'January', 'Q1'],
    ['2023-01-07', 'C', 'North', 227, 39, 'Bob', 'January', 'Q1'],
    ['2023-01-08', 'D', 'South', 783, 35, 'Alice', 'January', 'Q1'],
    ['2023-01-09', 'A', 'East', 352, 54, 'John', 'January', 'Q1'],
    ['2023-01-10', 'B', 'West', 740, 31, 'Mary', 'January', 'Q1']
]

columns = ['Date', 'Product', 'Region', 'Sales', 'Units', 'Rep', 'Month', 'Quarter']

df = pd.DataFrame(data, columns=columns)

print(df)

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    825     26   John  January      Q1
1  2023-01-02       B   West    611     51   Mary  January      Q1
2  2023-01-03       C  North    768     11    Bob  January      Q1
3  2023-01-04       D  South    665     71  Alice  January      Q1
4  2023-01-05       A   East    157     20   John  January      Q1
5  2023-01-06       B   West    436     43   Mary  January      Q1
6  2023-01-07       C  North    227     39    Bob  January      Q1
7  2023-01-08       D  South    783     35  Alice  January      Q1
8  2023-01-09       A   East    352     54   John  January      Q1
9  2023-01-10       B   West    740     31   Mary  January      Q1

In [15]:
pd.pivot_table(df,values="Sales",index='Region',columns='Product',aggfunc='median')

Product      A      B      C      D
Region
East     352.0    NaN    NaN    NaN
North      NaN    NaN  497.5    NaN
South      NaN    NaN    NaN  724.0
West       NaN  611.0    NaN    NaN

In [20]:
pivot2=pd.pivot_table(df, values=['Sales','Units'],index='Region',columns='Product')
pivot2

              Sales                                Units                   \
Product           A           B      C      D          A          B     C
Region
East     444.666667         NaN    NaN    NaN  33.333333        NaN   NaN
North           NaN         NaN  497.5    NaN        NaN        NaN  25.0
South           NaN         NaN    NaN  724.0        NaN        NaN   NaN
West            NaN  595.666667    NaN    NaN        NaN  41.666667   NaN


Product     D
Region
East      NaN
North     NaN
South    53.0
West      NaN

---
## cross tabs
used for counting purpose

In [22]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     3  0  0  0
North    0  0  2  0
South    0  0  0  2
West     0  3  0  0

---
## operations

In [26]:
df1=pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[10,20,30,40,50],
    'C':[100,200,300,400,500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [27]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [28]:
df1.shape

(5, 3)

In [29]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [30]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [31]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [32]:
df1['A']+10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

---
## applying some functions

In [33]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [35]:
def  square(x):
    return x**2

In [36]:
df1["B"].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [38]:
df1['B']=df1["B"].apply(square)

In [39]:
df1

   A     B    C
0  1   100  100
1  2   400  200
2  3   900  300
3  4  1600  400
4  5  2500  500