### pandas

In [1]:
!pip install pandas

Requirement already satisfied: pandas in ./.venv/lib/python3.14/site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in ./.venv/lib/python3.14/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import numpy as np 
import pandas as pd

---
### creating series and panda series

In [3]:
labels = ['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={1:10,2:20,3:30}

In [4]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [8]:
pd.Series(my_list,index=arr)

10    10
20    20
30    30
dtype: int64

---
### dataframes

### creating dataframes

In [ ]:
data = {
    'Name':['jhon', 'anna','peter','linda'],
    'age':[24,56,34,23],
    'city':['new york','mumbai','blr','deli'],
    'salary':[65000,88000,99000,78000]

}
df= pd.DataFrame(data)

    Name  age      city  salary
0   jhon   24  new york   65000
1   anna   56    mumbai   88000
2  peter   34       blr   99000
3  linda   23      deli   78000

In [10]:
df

    name  age         city  salary
0   john   23     new york    2000
1  jolli   24  los angeles    2500
2  peter   25      chicago    3000

In [13]:
data_list =[
    ['john',28,'new york',89000],
    ['ravi',89,'newziland',90000],
    ['gopal',45,'mumbai',70000],
    ['hari',13,'kerla',50000]
]
df2 = pd.DataFrame(data_list)
df2
columns = ["name","age","city","salary"]
df2=pd.DataFrame(data_list,columns=columns)
df2

    name  age       city  salary
0   john   28   new york   89000
1   ravi   89  newziland   90000
2  gopal   45     mumbai   70000
3   hari   13      kerla   50000

---
### selection and indexing of columns

In [14]:
df2

    name  age       city  salary
0   john   28   new york   89000
1   ravi   89  newziland   90000
2  gopal   45     mumbai   70000
3   hari   13      kerla   50000

In [15]:
df2['name']

0     john
1     ravi
2    gopal
3     hari
Name: name, dtype: str

In [16]:
df2['city']

0     new york
1    newziland
2       mumbai
3        kerla
Name: city, dtype: str

In [17]:
df2[['name','city']]

    name       city
0   john   new york
1   ravi  newziland
2  gopal     mumbai
3   hari      kerla

---
### creating new column

In [26]:
df2["Designation"]=["doctor","eng","eng","eng"]
df2

    name  age       city  salary Designation
0   john   28   new york   89000      doctor
1   ravi   89  newziland   90000         eng
2  gopal   45     mumbai   70000         eng
3   hari   13      kerla   50000         eng

---
### removing columns

In [27]:
df2

    name  age       city  salary Designation
0   john   28   new york   89000      doctor
1   ravi   89  newziland   90000         eng
2  gopal   45     mumbai   70000         eng
3   hari   13      kerla   50000         eng

In [28]:
df2.drop('Designation',axis=1)

    name  age       city  salary
0   john   28   new york   89000
1   ravi   89  newziland   90000
2  gopal   45     mumbai   70000
3   hari   13      kerla   50000

In [31]:
df2.drop('city',axis=1, inplace=True)

In [32]:
df2

    name  age  salary
0   john   28   89000
1   ravi   89   90000
2  gopal   45   70000
3   hari   13   50000

---
### selecting rows

In [33]:
df2

    name  age  salary
0   john   28   89000
1   ravi   89   90000
2  gopal   45   70000
3   hari   13   50000

In [34]:
df2.loc[0]

name       john
age          28
salary    89000
Name: 0, dtype: object

In [35]:
df2.loc[[0,1]]

   name  age  salary
0  john   28   89000
1  ravi   89   90000

---
### selecting subsets and rows and column

In [39]:
df2.loc[[0,1]][["name","salary"]]

   name  salary
0  john   89000
1  ravi   90000

---
### conditional selection

In [40]:
df2

    name  age  salary
0   john   28   89000
1   ravi   89   90000
2  gopal   45   70000
3   hari   13   50000

In [ ]:
# i only want to see who age is above 20

In [41]:
df2[df2["age"]>30]

    name  age  salary
1   ravi   89   90000
2  gopal   45   70000

In [43]:
#age above 30 and city must be paris
df2[(df2["age"]>30) & (df2["salary"]==90000)]

   name  age  salary
1  ravi   89   90000