In [1]:
import numpy as np 
import pandas as pd

### find missing data

In [21]:
data = {
    'A':[1,2,1,4,5],
    'B':[np.nan,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5]
}
df = pd.DataFrame(data)

In [22]:
df.isna()# true or false

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2  False  False  False   True
3  False  False   True   True
4  False  False   True  False

In [23]:
df.isna().sum()

A    0
B    1
C    2
D    3
dtype: int64

In [9]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

---
### removing missing data

In [24]:
df

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  NaN
2  1  3.0  3.0  NaN
3  4  4.0  NaN  NaN
4  5  5.0  NaN  5.0

In [27]:
df.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [28]:
df

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  NaN
2  1  3.0  3.0  NaN
3  4  4.0  NaN  NaN
4  5  5.0  NaN  5.0

In [29]:
df.dropna(thresh=3)

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  NaN
2  1  3.0  3.0  NaN
4  5  5.0  NaN  5.0

---
# filling the missing data

In [30]:
df

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  NaN
2  1  3.0  3.0  NaN
3  4  4.0  NaN  NaN
4  5  5.0  NaN  5.0

In [31]:
df.fillna(0)

   A    B    C    D
0  1  0.0  1.0  1.0
1  2  2.0  2.0  0.0
2  1  3.0  3.0  0.0
3  4  4.0  0.0  0.0
4  5  5.0  0.0  5.0

In [34]:
values = {'A':0,'B':100,'C':300,'D':400}
df.fillna(value=values)

   A      B      C      D
0  1  100.0    1.0    1.0
1  2    2.0    2.0  400.0
2  1    3.0    3.0  400.0
3  4    4.0  300.0  400.0
4  5    5.0  300.0    5.0

In [35]:
df

   A    B    C    D
0  1  NaN  1.0  1.0
1  2  2.0  2.0  NaN
2  1  3.0  3.0  NaN
3  4  4.0  NaN  NaN
4  5  5.0  NaN  5.0

In [36]:
df.fillna(df.mean())

   A    B    C    D
0  1  3.5  1.0  1.0
1  2  2.0  2.0  3.0
2  1  3.0  3.0  3.0
3  4  4.0  2.0  3.0
4  5  5.0  2.0  5.0

---
### merging joining and contcanation

### merging

In [44]:
employees = pd.DataFrame({
    'employee_id':[1,2,3,4,5],
    'name':['john','anna','peter','linda','bob'],
    'deparment': ('Hr','it','finance','it','hr')
})

salaries = pd.DataFrame({
    'employee_id':[1,2,3,5,6],
    'salary':[60000,80000,90000,30000,10000],
    'bonus':[5000,1000,3000,4000,7000]
})

In [39]:
employees

   employee_id   name deparment
0            1   john        Hr
1            2   anna        it
2            3  peter   finance
3            4  linda        it
4            5    bob        hr

In [45]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000   1000
2            3   90000   3000
3            5   30000   4000
4            6   10000   7000

In [48]:
pd.merge(employees,salaries,on='employee_id',how='inner')

   employee_id   name deparment  salary  bonus
0            1   john        Hr   60000   5000
1            2   anna        it   80000   1000
2            3  peter   finance   90000   3000
3            5    bob        hr   30000   4000

In [49]:
pd.merge(employees,salaries,on='employee_id',how='outer')

   employee_id   name deparment   salary   bonus
0            1   john        Hr  60000.0  5000.0
1            2   anna        it  80000.0  1000.0
2            3  peter   finance  90000.0  3000.0
3            4  linda        it      NaN     NaN
4            5    bob        hr  30000.0  4000.0
5            6    NaN       NaN  10000.0  7000.0

In [50]:
pd.merge(employees,salaries,on='employee_id',how='left')

   employee_id   name deparment   salary   bonus
0            1   john        Hr  60000.0  5000.0
1            2   anna        it  80000.0  1000.0
2            3  peter   finance  90000.0  3000.0
3            4  linda        it      NaN     NaN
4            5    bob        hr  30000.0  4000.0

In [51]:
pd.merge(employees,salaries,on='employee_id',how='right')

   employee_id   name deparment  salary  bonus
0            1   john        Hr   60000   5000
1            2   anna        it   80000   1000
2            3  peter   finance   90000   3000
3            5    bob        hr   30000   4000
4            6    NaN       NaN   10000   7000

---
### concatation

In [58]:
pf1 = pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2'],
    'C':['C0','C1','C3']
})
pf2 = pd.DataFrame({
    'A':['A3','A2','A3'],
    'B':['B3','B2','B0'],
    'C':['C3','C2','C1']

})
pf1
pf2

    A   B   C
0  A3  B3  C3
1  A2  B2  C2
2  A3  B0  C1

In [59]:
pf1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C3

In [60]:
pf2

    A   B   C
0  A3  B3  C3
1  A2  B2  C2
2  A3  B0  C1

In [63]:
pd.concat([pf1,pf2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C3
0  A3  B3  C3
1  A2  B2  C2
2  A3  B0  C1

In [64]:
pd.concat([pf1,pf2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A2  B2  C2
2  A2  B2  C3  A3  B0  C1

---
### joinging

In [66]:
fg1=pd.DataFrame({
    'name':['Alice','Bob','charlie'],

}, index=[1,2,3])

fg2=pd.DataFrame({
    'score':[85,90,75]
}, index=[2,3,4])

fg1

      name
1    Alice
2      Bob
3  charlie

In [67]:
fg1

      name
1    Alice
2      Bob
3  charlie

In [68]:
fg2

   score
2     85
3     90
4     75

In [70]:
fg1.join(fg2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  charlie   90.0

In [71]:
fg1.join(fg2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  charlie   90.0
4      NaN   75.0