# DATASET: India Cost of Living

In [6]:
import pandas as pd
import numpy as np
df = pd.read_csv('data.csv')
df

    Year    City  Food  Fuel   Rent  Transport  Utilities  Entertainment
0   2018  Mumbai   100    80  12000       2000       2500           1500
1   2019  Mumbai   105    82  12500       2100       2600           1600
2   2020  Mumbai   110    78  13000       1900       2700           1700
3   2021  Mumbai   120    90  13500       2200       2800           1800
4   2022  Mumbai   135   100  14500       2400       3000           2000
5   2023  Mumbai   150   115  16500       2900       3400           2400
6   2024  Mumbai   165   120  18000       3200       3600           2600
7   2018    Pune    90    75   8000       1500       2000           1200
8   2019    Pune    95    78   8200       1550       2100           1300
9   2020    Pune   100    76   8500       1500       2200           1400
10  2021    Pune   110    85   9000       1700       2300           1500
11  2022    Pune   120    95  10000       1900       2500           1700
12  2023    Pune   130   112  11500       2100       2600           1900
13  2024    Pune   145   118  13000       2300       2800           2100
14  2018   Delhi    95    78  10000       1800       2300           1400
15  2019   Delhi   100    80  10500       1900       2400           1500
16  2020   Delhi   105    79  11000       1800       2500           1600
17  2021   Delhi   115    88  12000       2000       2600           1700
18  2022   Delhi   125    98  13000       2200       2800           1900
19  2023   Delhi   140   115  14500       2600       3200           2200
20  2024   Delhi   155   118  16000       2900       3400           2400

---
## PROJECT QUESTIONS

### 1) Convert Date into datetime
pd.to_datetime:
 This is a pandas function that converts data → datetime format text/number → actual date
%Y what this means:
4-digit year (2018) it converts 4 digit year to date

In [9]:
df["Year"] = pd.to_datetime(df["Year"], format="%Y")
df

         Year    City  Food  Fuel   Rent  Transport  Utilities  Entertainment
0  2018-01-01  Mumbai   100    80  12000       2000       2500           1500
1  2019-01-01  Mumbai   105    82  12500       2100       2600           1600
2  2020-01-01  Mumbai   110    78  13000       1900       2700           1700
3  2021-01-01  Mumbai   120    90  13500       2200       2800           1800
4  2022-01-01  Mumbai   135   100  14500       2400       3000           2000
5  2023-01-01  Mumbai   150   115  16500       2900       3400           2400
6  2024-01-01  Mumbai   165   120  18000       3200       3600           2600
7  2018-01-01    Pune    90    75   8000       1500       2000           1200
8  2019-01-01    Pune    95    78   8200       1550       2100           1300
9  2020-01-01    Pune   100    76   8500       1500       2200           1400
10 2021-01-01    Pune   110    85   9000       1700       2300           1500
11 2022-01-01    Pune   120    95  10000       1900       2500           1700
12 2023-01-01    Pune   130   112  11500       2100       2600           1900
13 2024-01-01    Pune   145   118  13000       2300       2800           2100
14 2018-01-01   Delhi    95    78  10000       1800       2300           1400
15 2019-01-01   Delhi   100    80  10500       1900       2400           1500
16 2020-01-01   Delhi   105    79  11000       1800       2500           1600
17 2021-01-01   Delhi   115    88  12000       2000       2600           1700
18 2022-01-01   Delhi   125    98  13000       2200       2800           1900
19 2023-01-01   Delhi   140   115  14500       2600       3200           2200
20 2024-01-01   Delhi   155   118  16000       2900       3400           2400

---
## Group data city-wise
so groupby is easy here but we have got multiple useage of groupby data as finding mean sum etc 
but if you see second one i am using .agg functoin also as to get and be more specific about data i am agreagating it to particular data

In [16]:
df.groupby("City").mean()

,Year,Food,Fuel,Rent,Transport,Utilities,Entertainment
City,,,,,,,
Delhi,2020-12-31 13:42:51.428571,119.285714,93.714286,12428.571429,2171.428571,2742.857143,1814.285714
Mumbai,2020-12-31 13:42:51.428571,126.428571,95.000000,14285.714286,2385.714286,2942.857143,1942.857143
Pune,2020-12-31 13:42:51.428571,112.857143,91.285714,9742.857143,1792.857143,2357.142857,1585.714286

In [17]:
df.groupby("City").agg({
    "Food": "mean",
    "Fuel": "mean",
    "Rent": "max"
})

              Food       Fuel   Rent
City
Delhi   119.285714  93.714286  16000
Mumbai  126.428571  95.000000  18000
Pune    112.857143  91.285714  13000